server:
  port: 8080

spring:
  main:
    web-application-type: reactive

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5MDI1NTkwNiwiaWF0IjoxNjkwMjU1OTA2fQ.GWQAex6sG6gURGCpnl_bLcaXpUCa9RqBiTm0CfbpRQ8
